version: 0.0
os: linux 
files:
  - source: /
    destination: me/ec2-user
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    owner: root
    mode: 777
    type:
      - directory
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root